### ISSUE TITLE
Trying to setup a nodered WLED DDP -> LIFX bridge

### ISSUE THREAD

**Issue by mkaatman** [ristomatti/node-red-contrib-node-lifx#17]
Hello,

I'm working on a project where within WLED I setup a DDP node that points to nodered. This is working great and I see the DDP data coming in.

I wanted to try and use this plugin to translate that DDP into LIFX but I'm completely missing something obvious.

What is this server/hub configuration?

I setup just a name as the other fields say optional but when I click the search for light ID it says server not found or activated. This is probably obvious but I didn't see anything in the docs.

Thank you!
Matt

**Comment by ristomatti** [comment]
Have you used Node-RED before? You'll need one configuration node that is responsible for detecting the LIFX devices on your local network and acts as the bridge between the Node-RED Web UI and the extension. The server is exactly that. 

You can add it from the settings dialog of either **node-lifx-in** or **node-lifx-out** node. The rest of the in/out nodes can use the already existing config node.

I would suggest starting with a **node-lifx-in** node, as you can then easily see if the lights are detected. It's been a while since I set this up, but if I remember correctly the exact procedure is like this:

1. Drag a **node-lifx-in** node in your flow
2. Add a new LIFX server (or edit one if you've already created it).
3. The default settings should be ok in most scenarios, so you can just click "Add".
4. Give some name for the input node, click "Done" and then deploy the changes.
5. Open the settings for the input node you've added and click the 🔍 icon. If your light(s) appear on the list it indicates you're good to go.

Something is wrong if no lights show up. Unless you're running a more advanced network setup (e.g. use VLAN's), the most likely reason would be that you've setup a firewall on the computer running Node-RED. To fix this, you'll need to allow inbound connections from UDP port 56700.

In case you want to first verify the connectivity w/o Node-RED, the easiest way I can think of would be using this command line tool: https://github.com/ristomatti/lifxsh. It uses the same library as the Node-RED plugin, so if it can discover your lights, it should work in Node-RED as well.

**Comment by ristomatti** [comment]
The commend line tool is also useful way to get a quick overview of your lights (their state, IP address and unique ID):

![image](https://github.com/user-attachments/assets/747a6b14-f8c2-4693-ac13-44071f52f7da)

**Comment by mkaatman** [comment]
Hey @ristomatti thanks for this great info. I've used nodered a bit but I'm still quite a beginner.

>  You'll need one configuration node that is responsible for detecting the LIFX devices on your local network and acts as the bridge between the Node-RED Web UI and the extension

Excuse my denseness, but it's still not quite parsing. What device/software am I pointing at that does this? Is it just a single bulb that can detect the rest?

> In case you want to first verify the connectivity w/o Node-RED, the easiest way I can think of would be using this command line tool: https://github.com/ristomatti/lifxsh.

Great tip! I will try that out.

On the other front, I have a NR function that's decoding DDP data. :)

Spec: http://www.3waylabs.com/ddp/

I think I'm going to make two encoders.
1. One that talks to any bulb in HA using the HA API
2. One that talks to node LIFX 

```javascript
const buffer = msg.payload
if (buffer.length < 10) throw new Error('Buffer too short to contain a valid DDP packet header');

const packet = {}
// Byte 0: flags V V x T S R Q P
const byte0 = buffer[0];
packet.version = (byte0 >> 6) & 0x03; // Bits 7-6: V V
packet.T = (byte0 >> 4) & 0x01;       // Bit 4: T
packet.S = (byte0 >> 3) & 0x01;       // Bit 3: S
packet.R = (byte0 >> 2) & 0x01;       // Bit 2: R
packet.Q = (byte0 >> 1) & 0x01;       // Bit 1: Q
packet.P = byte0 & 0x01;              // Bit 0: P

// Byte 1: x x x x n n n n
const byte1 = buffer[1];
packet.sequence = byte1 & 0x0F; // Bits 3-0: n n n n

// Byte 2: Data type
packet.dataType = buffer[2];

// Byte 3: Destination ID
packet.destinationID = buffer[3];

// Bytes 4-7: Data offset (32-bit MSB first)
packet.dataOffset = buffer.readUInt32BE(4);

// Bytes 8-9: Data length (16-bit MSB first)
packet.dataLength = buffer.readUInt16BE(8);

let offset = 10;

// Timecode field
if (packet.T) {
    if (buffer.length < 14) throw new Error('Buffer too short to contain timecode');
    packet.timecode = buffer.readUInt32BE(10);
    offset = 14;
}

// Data field
const expectedDataLength = packet.dataLength;
const remainingBufferLength = buffer.length - offset;
if (expectedDataLength > remainingBufferLength) {
    throw new Error('Data length exceeds remaining buffer size');
}

packet.data = buffer.slice(offset, offset + expectedDataLength);
msg.payload = packet;
return msg;
```

**Comment by mkaatman** [comment]
Here's a mockup of what I'm going for. 
![image](https://github.com/user-attachments/assets/3b625456-583d-431e-b303-667dae4c649b)

**Comment by ristomatti** [comment]
> Excuse my denseness, but it's still not quite parsing. What device/software am I pointing at that does this? Is it just a single bulb that can detect the rest?

Basically you shouldn't have to point anything to anything. This is what happens on the LIFX side of thing after the flow is deployed:

1. Server node binds to the given network interface, or by default all interfaces (address `0.0.0.0`).
2. Server node then sends out a broadcast "discovery" packet over UDP
3. LIFX devices/lights that receive the packet, respond by sending a UDP packet that has it's IP/MAC address etc.

The term "server" might be what's misleading here. I'm not exactly sure how the original author of this plugin came up with it. From the network perspective, the LIFX lighgts act as servers and the Node-RED node acts as client. This is why the underlying library is called [lifx-lan-client](https://github.com/node-lifx/lifx-lan-client/) after all.

Aside, you might want to take a look at [node-red-contrib-buffer-parser](https://flows.nodered.org/node/node-red-contrib-buffer-parser) if you want to try to do things in a more Node-RED way. :slightly_smiling_face:

**Comment by mkaatman** [comment]
I actually did start using buffer-parser after that screenshot!

Here's what I'm getting. I add a server and click find:
![image](https://github.com/user-attachments/assets/f5d974b5-81de-455e-b118-260275c64f28)

![image](https://github.com/user-attachments/assets/31a94599-bf4f-4e31-a58f-85cb33d924a6)

I guess it's time to breakout tcpdump and see if some packet is getting blocked.

**Comment by ristomatti** [comment]
Is that after you've deployed the flow? The error tells the in/out nodes can't detect the server node.

**Comment by ristomatti** [comment]
Ah sorry, I read this too quickly. Try manually setting the address to `0.0.0.0` and broadcast to `255.255.255.255` and see if it helps.

Did you try `lifxsh` on the same computer/server or a different one?

**Comment by mkaatman** [comment]
- No difference using the manually set address and broadcast.
- lifxsh running on same server
- Lights are on same subnet as NR
**- Is that after you've deployed the flow? Winner winner chicken dinner!**

I'm in business now. TY a ton!

**Comment by ristomatti** [comment]
Ok to close?

**Comment by mkaatman** [comment]
Yes! Hopefully this issue will help someone in the future.
